### ISSUE TITLE
Test error with scikit-learn 0.24.0

### ISSUE THREAD

**Issue by rmontanana** [Doctorado-ML/STree#21]
======================================================================
FAIL: test_is_a_sklearn_classifier (stree.tests.Stree_test.Stree_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rof/src/github.com/Doctorado-ML/STree/stree/tests/Stree_test.py", line 135, in test_is_a_sklearn_classifier
    check_estimator(Stree())
  File "/home/rof/.pyenv/versions/3.8.6/lib/python3.8/site-packages/sklearn/utils/estimator_checks.py", line 547, in check_estimator
    check(estimator)
  File "/home/rof/.pyenv/versions/3.8.6/lib/python3.8/site-packages/sklearn/utils/_testing.py", line 308, in wrapper
    return fn(*args, **kwargs)
  File "/home/rof/.pyenv/versions/3.8.6/lib/python3.8/site-packages/sklearn/utils/estimator_checks.py", line 921, in check_sample_weights_invariance
    assert_allclose_dense_sparse(X_pred1, X_pred2, err_msg=err_msg)
  File "/home/rof/.pyenv/versions/3.8.6/lib/python3.8/site-packages/sklearn/utils/_testing.py", line 415, in assert_allclose_dense_sparse
    assert_allclose(x, y, rtol=rtol, atol=atol, err_msg=err_msg)
  File "/home/rof/.pyenv/versions/3.8.6/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/rof/.pyenv/versions/3.8.6/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-09
For Stree, a zero sample_weight is not equivalent to removing the sample
Mismatched elements: 8 / 16 (50%)
Max absolute difference: 1
Max relative difference: 1.
 x: array([1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2])
 y: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**Comment by rmontanana** [comment]
Found a possible solution: 
```python
-        # solve WARNING: class label 0 specified in weight is not found
-        # in bagging
+        # Remove samples 0 weighted
         if any(sample_weight == 0):
             indices = sample_weight == 0
-            y_next = y[~indices]
-            # touch weights if removing any class
-            if np.unique(y_next).shape[0] != self.n_classes_:
-                sample_weight += 1e-5
+            Xs = Xs[~indices, :]
+            X = X[~indices, :]
+            y = y[~indices]
+            sample_weight = sample_weight[~indices]
```

Code would be:
```python
# Remove samples 0 weighted
if any(sample_weight == 0):
    indices = sample_weight == 0
    Xs = Xs[~indices, :]
    X = X[~indices, :]
    y = y[~indices]
    sample_weight = sample_weight[~indices]
```
Note: *ensembles results*

**Comment by rmontanana** [comment]
Proposed solution
```python
if any(sample_weight == 0):
    indices_zero = sample_weight == 0
    X = X[~indices_zero, :]
    y = y[~indices_zero]
    sample_weight = sample_weight[~indices_zero]
# if any(sample_weight == 0):
#     indices_zero = sample_weight == 0
#     removed_class = np.unique(y[~indices_zero]).shape[0] < 2
# else:
#     removed_class = False

if np.unique(y).shape[0] == 1:
    # if np.unique(y).shape[0] < 2 or removed_class:


def test_mask_samples_weighted_zero(self):
    X = np.array(
        [
            [1, 1],
            [1, 1],
            [1, 1],
            [2, 2],
            [2, 2],
            [2, 2],
            [3, 3],
            [3, 3],
            [3, 3],
        ]
    )
    y = np.array([1, 1, 1, 2, 2, 2, 5, 5, 5])
    yw = np.array([1, 1, 1, 5, 5, 5, 5, 5, 5])
    w = [1, 1, 1, 0, 0, 0, 1, 1, 1]
    model1 = Stree().fit(X, y)
    model2 = Stree().fit(X, y, w)
    predict1 = model1.predict(X)
    predict2 = model2.predict(X)
    self.assertListEqual(y.tolist(), predict1.tolist())
    self.assertListEqual(yw.tolist(), predict2.tolist())
    self.assertEqual(model1.score(X, y), 1)
    self.assertAlmostEqual(model2.score(X, y), 0.66666667)
    self.assertEqual(model2.score(X, y, w), 1)
