### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 10272: character maps to <undefined>

### ISSUE THREAD

**Issue by Semiu** [Doctorado-ML/STree#57]
A pip install `pip install git+https://github.com/doctorado-ml/stree` resulted in a `UnicodeDecodeError`.

This is the entire traceback output:

```
Traceback (most recent call last):
        File "C:\Users\Admin\Documents\cve-automated-detection\.cvedev\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Admin\Documents\cve-automated-detection\.cvedev\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Admin\Documents\cve-automated-detection\.cvedev\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-6ebp7ezh\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-6ebp7ezh\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-6ebp7ezh\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-6ebp7ezh\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 33, in <module>
        File "<string>", line 7, in readme
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 10272: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```
Any pointer to fixing this would be appreciated. Thank you.

**Comment by rmontanana** [comment]
Hi!

I see that you are using Python 3.10.3 on Windows, I will try to install in an environment similar as yours to see what happens, as long as it is working nicely in my linux and my MacOS computers, even with this Python version.

Meanwhile I would like to know a little more of your environment

Could you update your Python version?
Are you using conda?

**Comment by rmontanana** [comment]
Just installed miniconda (with Python 3.12) on a windows 11 box and got the same message as yours,

        File "C:\Users\rmont\miniconda3\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 10272: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


### **But tried installing Stree with the following command and it worked like a charm!**

(base) PS D:\> pip install Stree
Collecting Stree
  Using cached STree-1.3.2-py3-none-any.whl.metadata (17 kB)
Collecting scikit-learn>0.24 (from Stree)
  Downloading scikit_learn-1.4.1.post1-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting mufs (from Stree)
  Downloading MUFS-0.1.3-py3-none-any.whl.metadata (2.8 kB)
Collecting numpy<2.0,>=1.19.5 (from scikit-learn>0.24->Stree)
  Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 1.1 MB/s eta 0:00:00
Collecting scipy>=1.6.0 (from scikit-learn>0.24->Stree)
  Downloading scipy-1.12.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 3.1 MB/s eta 0:00:00
Collecting joblib>=1.2.0 (from scikit-learn>0.24->Stree)
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn>0.24->Stree)
  Downloading threadpoolctl-3.3.0-py3-none-any.whl.metadata (13 kB)
Using cached STree-1.3.2-py3-none-any.whl (26 kB)
Downloading scikit_learn-1.4.1.post1-cp312-cp312-win_amd64.whl (10.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.6/10.6 MB 22.6 MB/s eta 0:00:00
Using cached MUFS-0.1.3-py3-none-any.whl (13 kB)
Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.5/15.5 MB 27.3 MB/s eta 0:00:00
Downloading scipy-1.12.0-cp312-cp312-win_amd64.whl (45.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 MB 21.8 MB/s eta 0:00:00
Downloading threadpoolctl-3.3.0-py3-none-any.whl (17 kB)
Installing collected packages: threadpoolctl, numpy, joblib, scipy, scikit-learn, mufs, Stree
Successfully installed Stree-1.3.2 joblib-1.3.2 mufs-0.1.3 numpy-1.26.4 scikit-learn-1.4.1.post1 scipy-1.12.0 threadpoolctl-3.3.0
(base) PS D:\>

### Hope this works for you as well!
